### ISSUE TITLE
使用电机作为滚轮时滚动行数不一致的问题

### ISSUE THREAD

**Issue by Syfer-Omestics** [xingrz/zmk-config_helloword_hw-75#15]
典型复现方式（其实只要将电机设置为”滚动“都可以复现，这样设置只是为了让复现效果更明显）：
· 在edge或chrome上打开一份长PDF文档
· 在上位机中将电机的滚动偏好设置为”惯性“，将”步数“调整为8，”力度“默认
· 分别快速向上和向下拨动滚轮，可以发现长文档页面向下滚动的速度快于向上滚动的速度。
· 以一份100页的pdf为例，自顶向下完全浏览需要约13秒，而反过来需要约30秒。速度的区别大约在两倍。

如能修复，感谢大佬！

**Comment by xingrz** [comment]
惯性是靠算法模拟出来的，本身因为传感器的噪声，速度计算会有一定的误差。

作为滚轮时，建议用齿轮或者平滑模式。
