### ISSUE TITLE
扩展模块电机向上和向下滚动一次的行数不一致

### ISSUE THREAD

**Issue by Syfer-Omestics** [xingrz/zmk-config_helloword_hw-75#16]
使用齿轮模式，确保只触发一次滚动，也可以明显发现向下滚动的行数是向上滚动行数的两倍。而音量和亮度模式则不会
![Untitled video - Made with Clipchamp](https://github.com/xingrz/zmk-config_helloword_hw-75/assets/98811046/c7ea8f62-fdca-4425-abd0-977423b9781a)

**Comment by xingrz** [comment]
> 而音量和亮度模式则不会

那更加坐实了是你电脑的设置问题了。

这三个功能本质都只是一个 HID 上报，没有什么不同。

要么就是你改了 keymap 里的步数，自己忘了。

https://github.com/xingrz/zmk-config_helloword_hw-75/blob/e6201ef90032e0adb0559108a4e6fdff46104462/config/hw75_dynamic.keymap#L32

**Comment by Syfer-Omestics** [comment]
> 
![Untitled video - Made with Clipchamp (2)](https://github.com/xingrz/zmk-config_helloword_hw-75/assets/98811046/157b1c0b-b267-4ba1-8629-52351ee64dcd)
我使用了三种模式来使用鼠标滚轮，分别是鼠标自带的滚轮按钮、将键盘上的W和S映射为鼠标滚轮上/鼠标滚轮下、使用扩展模块电机的”滚动“模式。从结果来看，只有扩展模块会出现上述问题。是否是因为MW_DN(1)出于某些原因被触发两次？还是说这是本人硬件电机的问题？感谢~

**Comment by Syfer-Omestics** [comment]
> > 
> 
> ![Untitled video - Made with Clipchamp (2)](https://user-images.githubusercontent.com/98811046/239821564-157b1c0b-b267-4ba1-8629-52351ee64dcd.gif) 我使用了三种模式来使用鼠标滚轮，分别是鼠标自带的滚轮按钮、将键盘上的W和S映射为鼠标滚轮上/鼠标滚轮下、使用扩展模块电机的”滚动“模式。从结果来看，只有扩展模块会出现上述问题。是否是因为MW_DN(1)出于某些原因被触发两次？还是说这是本人硬件电机的问题？感谢~

另外我是用的是最新版的扩展模块固件，没有自行更改过参数qwq
