### ISSUE TITLE
亮度调整功能无效

### ISSUE THREAD

**Issue by XXTMTA** [xingrz/zmk-config_helloword_hw-75#17]
因为电脑显示器不支持Windows调光，麻烦考虑像Twinkle Tray那种，用DDC/Cl调光

**Comment by xingrz** [comment]
固件发出的是符合 HID 规范的按键码，不会向你的电脑安装软件。如果你的电脑不支持，可以自己改 keymap 把这个功能隐藏掉。或者自己找个别的软件去实现你所说的Twinkle Tray。
