### ISSUE TITLE
如何获得最新固件的源码 如何编译uf2格式的文件

### ISSUE THREAD

**Issue by tr1912** [xingrz/zmk-config_helloword_hw-75#19]
在这个仓库没有看到源码，稚晖君的代码不知道是不是最新固件，所以需要怎么搞

**Comment by xingrz** [comment]
> 在这个仓库没有看到源码

这个仓库目光所及到处都是源码，不知道这个问题从何而来。

编译可参考[这里](https://github.com/xingrz/zmk-config_helloword_hw-75/tree/master/config/boards/arm/hw75_keyboard#%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91)和[这里](https://github.com/xingrz/zmk-config_helloword_hw-75/tree/master/config/boards/arm/hw75_dynamic#%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91)。

> 稚晖君的代码不知道是不是最新固件

这个仓库是基于相同硬件的全新实现，没有使用稚晖君的代码，无法比较新和旧。

**Comment by tr1912** [comment]
好的，感谢回复，之前因为网络问题没有打开config文件夹，clone到本地才看到，
另外我用clion打开之后，用cmake报错
`CMake Error at app/CMakeLists.txt:4 (zephyr_include_directories):
  Unknown CMake command "zephyr_include_directories".`
请问这个要怎么解决

**Comment by xingrz** [comment]
照着二次开发步骤来。
