### ISSUE TITLE
拓展模块断电丢失配置

### ISSUE THREAD

**Issue by tqro** [xingrz/zmk-config_helloword_hw-75#20]
键盘主体使用 ydkb, 拓展使用了您这个，但每次配置灯效、电机模式后，只要断电就会恢复到默认，需要将键盘本体也刷为您这个固件才能断电保存吗？

**Comment by xingrz** [comment]
Fixed in 60290181f5

**Comment by xingrz** [comment]
https://github.com/xingrz/zmk-config_helloword_hw-75/releases/tag/20231018.1
