### ISSUE TITLE
键盘长时间不活动导致死机

### ISSUE THREAD

**Issue by Chenshengshu** [xingrz/zmk-config_helloword_hw-75#21]
键盘长时间不活动时，再次使用的时候无法激活，只能重新插拔电源恢复，并且按Fn插拔电源无法弹出虚拟U盘

**Comment by xingrz** [comment]
我放公司的键盘已经起码三个月没拔了…

**Comment by Chenshengshu** [comment]
无法弹出虚拟U盘遇到过吗？按着Fn有时候会弹出扩展模块的虚拟U盘

**Comment by xingrz** [comment]
进入Bootloader唯一的途径是按着Fn键重新上电。如果你只是普通按着Fn也能进Bootloader的话，那只能怀疑是供电不稳定导致芯片掉电重启了。

**Comment by Chenshengshu** [comment]
普通按着Fn不会进入 Bootloader， 按着Fn重新上电的时候有时候会导致弹出扩展模块的Bootloader

**Comment by xingrz** [comment]
你怎么判断它是扩展模块的Bootloader而不是键盘的Bootloader呢？

**Comment by Chenshengshu** [comment]
名称以及里面INFO_UF2.TXT文件 ，Model: HelloWord HW-75 Dynamic (bootloader)

**Comment by xingrz** [comment]
十分诡异而有趣。但万事都可以归咎到供电问题。

**Comment by Chenshengshu** [comment]
感谢解答，我再检查一遍
