### ISSUE TITLE
拓展开关模式无法记录上位机设定值

### ISSUE THREAD

**Issue by Xiangjincheng** [xingrz/zmk-config_helloword_hw-75#24]
我自己增加了音乐启停功能，但是开关模式在每次掉电之后都会复位为默认模式，不知道哪里可以更改，望指点一二

**Comment by xingrz** [comment]
1. 请更新到最新一个版本（作为一个 bug report，你没有告诉我你用的版本，我只能猜测你用的是旧版）
2. 为了减缓 Flash 写入磨损，所有设置都会延迟到 1 分钟写入

**Comment by Xiangjincheng** [comment]
不好意思，这是我更改您程序重新编译碰到的问题，我使用的是最新的源代码在拓展keymap中增加了一个音乐播放功能，上位机更改模式无法写入，因此想请教一下。我更改的keymap如下：

	keymap {
		compatible = "zmk,keymap-ext", "zmk,keymap";

		volume {
			label = "音量";
			icon = [EE A1 BA];
			bindings = <&lvkp LV_KEY_PREV &lvkp LV_KEY_NEXT>;
			sensor-bindings = <&inc_dec_kp C_VOL_UP C_VOL_DN>;
		};

		change_music {
			label = "切歌";
			icon = [EE A3 8D];
			bindings = <&trans &trans>;
			sensor-bindings = <&inc_dec_kp C_NEXT C_PREVIOUS>;
		};

		music_start_stop {
			label = "音乐";
			icon = [EE A0 8F];
			bindings = <&trans &trans>;
			sensor-bindings = <&inc_dec_kp C_PLAY_PAUSE C_PLAY_PAUSE>;
		};

		scroll {
			label = "滚动";
			icon = [EE AC 89];
			bindings = <&trans &trans>;
			sensor-bindings = <&inc_dec_mw MW_DN(1) MW_UP(1)>;
		};

		arrow_horizontal {
			label = "左右";
			icon = [EE 9B AB];
			bindings = <&trans &trans>;
			sensor-bindings = <&inc_dec_kp LEFT RIGHT>;
		};

	};

音乐和左右无法写入switch模式

**Comment by xingrz** [comment]
> 2\. 为了减缓 Flash 写入磨损，所有设置都会延迟到 1 分钟写入

强调 ↑↑↑

当然你也可以让它默认就处于某个模式，而不是在 ZMKX.app 上手动更改。

```dts
tasks {
	label = "窗口";
	icon = [EF 85 9E];
	bindings = <&trans &trans>;
	sensor-bindings = <&switch_screens>;
	profile = <&profile_spring>;
};
```

**Comment by Xiangjincheng** [comment]
写入磨损我做了测试发现不是这个问题，我把5个模式都改成了switch模式，过了大概三四分钟重新上电，音乐和左右无法写入switch模式，其他三个正常写入了。

**Comment by Xiangjincheng** [comment]
> 当然你也可以让它默认就处于某个模式，而不是在 ZMKX.app 上手动更改。
> 
> ```
> tasks {
> 	label = "窗口";
> 	icon = [EF 85 9E];
> 	bindings = <&trans &trans>;
> 	sensor-bindings = <&switch_screens>;
> 	profile = <&profile_spring>;
> };
> ```
这个方法也可以解决我现在的困扰，感谢解答
