### ISSUE TITLE
没有晴间多云的图片导致报错

### ISSUE THREAD

**Issue by WOC5207** [xingrz/zmk-config_helloword_hw-75#25]
![QQ截图20231212003149](https://github.com/xingrz/zmk-config_helloword_hw-75/assets/58818146/fa78cd5c-a8ac-4f1b-83ab-b51ff1ad7dfd)
Request了晴间多云，但是找不到图片

**Comment by xingrz** [comment]
不属于固件问题。

**Comment by WOC5207** [comment]
我的问题，回复错repo了
