### ISSUE TITLE
請問能有繁體中文或英文的版本嗎

### ISSUE THREAD

**Issue by bkes994104** [xingrz/zmk-config_helloword_hw-75#27]
請問能有繁體中文或英文的版本嗎
謝謝!

**Comment by xingrz** [comment]
如果你是指 zmkx.app 的话，它会自动根据你的浏览器设置选择语言，也可以通过右上角的菜单选择：

<img width="1132" alt="image" src="https://github.com/xingrz/zmk-config_helloword_hw-75/assets/288288/30587131-80d2-4666-ac6e-d0f7cfb6ce7a">

如果你是指固件的话，可自行修改 [hw75_dynamic.keymap](https://github.com/xingrz/zmk-config_helloword_hw-75/blob/master/config/hw75_dynamic.keymap) 中的 `label` 标签。
