### ISSUE TITLE
使用 ST-Link烧录helloword_16k.hex  引导程序，win系统提示该设备的驱动程序未被安装。

### ISSUE THREAD

**Issue by yyao00** [xingrz/zmk-config_helloword_hw-75#28]

**Comment by yyao00** [comment]
使用 ST-Link烧录helloword_16k.hex  引导程序，win系统提示该设备的驱动程序未被安装。

**Comment by xingrz** [comment]
不属于固件 bug，个人也没用过 Windows 和 ST-LINK，无法提供帮助。请咨询你的售后客服或者在交流群里问别人。
