### ISSUE TITLE
请问能够支持三色墨水屏嘛

### ISSUE THREAD

**Issue by Untakename** [xingrz/zmk-config_helloword_hw-75#4]
请问能否适配三色墨水屏？墨水屏型号HinkE029A10

**Comment by xingrz** [comment]
[驱动](https://github.com/xingrz/zmk-config_helloword_hw-75/blob/master/config/drivers/display/ssd16xx.c)是有的，需要自己适配参数。但是上位机下发来的图像已经抽成 1 bpp 的黑白序列了，需要自己改。
