### ISSUE TITLE
键盘固件断电再上电丢失问题

### ISSUE THREAD

**Issue by ahfynjj** [xingrz/zmk-config_helloword_hw-75#5]
键盘是小白君的车，刷了UF2 bootloader，偏移是0x08000000，最新固件，每次断线再插电就会丢失固件，需要重新刷鞋固件以后才能使用。

**Comment by xingrz** [comment]
固件都丢了，显然不会是固件自身的问题…

**Comment by xingrz** [comment]
我突然理解你所说的「丢固件」可能只是进了 Bootloader 模式…这是 keebpro bootloader 的一个 bug，重新插拔一下 USB 线就可以了。当然，你也可以看下他有没有更新。

**Comment by ahfynjj** [comment]
确实是这样，那怕是休眠了也会丢固件，重新插拔USB就进入到了U盘刷固件模式。

**Comment by xingrz** [comment]
> 确实是这样，那怕是休眠了也会丢固件，重新插拔USB就进入到了U盘刷固件模式。

首先，固件没丢，它一直在那，好好的。只不过 keebpro 的 bootloader 会误进更新模式而已。
