### ISSUE TITLE
新功能的建议

### ISSUE THREAD

**Issue by isTrih** [xingrz/zmk-config_helloword_hw-75#6]
我的瀚文配了一些个奇怪配色的键帽，所以我想肯定还有其他人配奇怪的配色，所以想提一个建议：
主体：主题右下角的状态指示灯可以换其他色（因为没有上位机，也可以说明一下在哪里，我自己去改）
拓展：状态指示灯（俩按钮右边的）可以换其他色的功能

**Comment by xingrz** [comment]
正因为它是指示灯，所以它的颜色是固定的。

如果你有需求，可以自己改 https://github.com/xingrz/zmk-config_helloword_hw-75/blob/master/config/app/indicator.c#L28

**Comment by xingrz** [comment]
另外，上位机的地址是 https://zmkx.app
