### ISSUE TITLE
电机演示无法打开

### ISSUE THREAD

**Issue by Chenshengshu** [xingrz/zmk-config_helloword_hw-75#7]

**Comment by xingrz** [comment]
请详细描述你遇到的问题。

**Comment by HipHopCoderS** [comment]
演示，感觉每个模式下，电机都是顺滑的，不知道是不是电机的问题，同样的另一个Hw75 就很丝滑，可以演示

**Comment by xingrz** [comment]
> 演示，感觉每个模式下，电机都是顺滑的

有两种可能：1.电机电源没接或者脱焊。2.12V使能电路断路
