### ISSUE TITLE
拓展模块异常

### ISSUE THREAD

**Issue by sxz1234** [xingrz/zmk-config_helloword_hw-75#8]
您好，我的拓展模块是用的立创上稚晖君开源的pcb，自己修改墨水屏排线座的位置（仅移动），使得可以配合咸鱼上的墨水屏。tinyuf2和zmk固件都是用这个github仓库里最新的（20230216.1的zmk固件，20230127.1的tinyuf2）。我将tinyuf2 bootloader通过stlink烧录进去后可以正常进入虚拟磁盘中，并且可以将zmk固件复制进虚拟磁盘中。当复制进度条到100%后，可以听到电脑连接断开的声音。之后无论等多久，拓展模块都无任何反应（rgb，oled都不亮，电机不转）。试了很多次，甚至更换过去zmk固件；更换杰哥升级助手bootloader，都试过了，不行。
目前可以使用的只有之前用咸鱼墨水屏及三色墨水屏的那位大哥发的固件可以用，功能也正常（oled可以显示，电机可以转，墨水屏可以显示）。
按道理来说，不用咸鱼墨水屏对应的固件应该只有墨水屏不能使用吧？为什么现在都不能用呢？
键盘主体pcb是之前小白开团的，仅pcb，自己焊接。用的也是您仓库里的zmk固件及[keeb.pro]的bootloader。键盘主体功能均正常。

**Comment by xingrz** [comment]
> 目前可以使用的只有之前用咸鱼墨水屏及三色墨水屏的那位大哥发的固件可以用，功能也正常（oled可以显示，电机可以转，墨水屏可以显示）。
> 按道理来说，不用咸鱼墨水屏对应的固件应该只有墨水屏不能使用吧？为什么现在都不能用呢？

有一种可能是，你用的墨水屏和原版设计的引脚不一样，导致短路…试试拔掉墨水屏再上电？

**Comment by sxz1234** [comment]
我测试一下

**Comment by xingrz** [comment]
另外，你可以尝试 https://github.com/xingrz/zmk-config_helloword_hw-75/tree/master/config/boards/arm/hw75_dynamic#%E6%97%A5%E5%BF%97 的做法看一下启动日志…

**Comment by sxz1234** [comment]
解决了，我把墨水屏拿下来，oled，电机，rgb就都正常了，谢谢
