### ISSUE TITLE
关于在app网页中查看电机多种模式的效果和电机啸叫

### ISSUE THREAD

**Issue by wlzxzq** [xingrz/zmk-config_helloword_hw-75#9]
在此效果下，电机并不能如模式标题所示的 弹簧、阻尼灯，电机运动的不正常。这个是与什么相关呢？我采用的是 2204原版电机，非一体。同时，电机会有相对小的啸叫。

**Comment by xingrz** [comment]
啸叫可能是12V供电没供上。

**Comment by wlzxzq** [comment]
电压经过测量应该是12v。3.3v 5v都是正常
